#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../autoload.php')) {
    include_once __DIR__ . '/../autoload.php';
} else {
    include_once __DIR__ . '/../vendor/autoload.php';
}

$runner = new \PowerJson\Runner(__DIR__, new \Commando\Command());
echo $runner->run() . PHP_EOL;
