#!/usr/bin/env php
<?php

// if installed as package
if (file_exists(__DIR__ . '/../../../autoload.php')) {
    include_once __DIR__ . '/../../../autoload.php';
} else {
    include_once __DIR__ . '/../vendor/autoload.php';
}

$runner = new \PowerJson\Runner();
$baseConfiguration = getcwd() . DIRECTORY_SEPARATOR . \PowerJson\Runner::LOCAL_CONFIG_FN;
if (!file_exists($baseConfiguration)) {
    $runner->setCommand(new \Commando\Command);
}
echo $runner->run() . PHP_EOL;
